apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  replicas: 1

  template:
    metadata:
      labels:
        app: go-hpa
        tier: go-hpa

    spec:
      containers:
        - name: go-hpa
          image: img-go-hpa-deployment
          #command: ["/bin/sh", "-c", "while true; do wget -q -O- http://go-hpa.default.svc.cluster.local; done;"]
          ports:
            - containerPort: 8000
              hostPort: 80

          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"

